# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and deploy to internal track"
  lane :internal do
    gradle(task: "clean bundleRelease")
    
    upload_to_play_store(
      package_name: "com.aprmp.fastlane_deployment",
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      release_status: "draft"
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build and deploy to production"
  lane :production do
    gradle(task: "clean bundleRelease")

    upload_to_play_store(
      package_name: "com.aprmp.fastlane_deployment",
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
